version: '3.8'

services:
  mysqldb:
    image: mysql:latest
    container_name: 'mysql_service'
    restart: always
    env_file:
      - '.docker.env'
    ports:
      - '3306:33060'
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_USER}
    volumes:
      - ./docker_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: 'phpmyadmin_service'
    restart: always
    ports:
      - '8085:80'
    env_file:
      - '.docker.env'
    environment:
      - PMA_HOST=${PMA_HOST}
      - PMA_USER=${PMA_USER}
      - PMA_PASSWORD=${PMA_PASSWORD}
    depends_on:
      - mysqldb

volumes:
  docker_data: {}
